jessie:
  tags:
    - jessie
  before_script:
    - pip3 install --upgrade -r tests/requirements.txt
  script:
    - coverage run --source ./ -m unittest -v tests.test_acme_dns_tiny tests.test_acme_account_rollover tests.test_acme_account_deactivate
    - coverage report --include=acme_dns_tiny.py,tools/acme_account_rollover.py,tools/acme_account_deactivate.py
    - coverage html

stretch:
  tags:
    - stretch
  before_script:
    - pip3 install --upgrade -r tests/requirements.txt
  script:
    - coverage run --source ./ -m unittest -v tests.test_acme_dns_tiny tests.test_acme_account_rollover tests.test_acme_account_deactivate
    - coverage report --include=acme_dns_tiny.py,tools/acme_account_rollover.py,tools/acme_account_deactivate.py
    - coverage html
  artifacts:
    paths:
     - htmlcov
